Repository PriyaGhosal/BuddyTrail, pull requests merged in 2024-10, with the labels that each got.

#175 added bots
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/Pull_Request_Template.md
  .github/assets/gssoc24.png
  .github/workflows/auto-assign.yml
  .github/workflows/autocomment-iss-close.yml
  .github/workflows/autocomment-issue.yml
  .github/workflows/autocomment-pr-merge.yml
  .github/workflows/autocomment-pr-raise.yml
  .github/workflows/autocomment-wait.yml
  .github/workflows/autolabelissue.yml
  .github/workflows/close-old-issue.yml
Labels: hacktoberfest-accepted, gssoc-ext

#430 solve the bug added the hover effect
  index.html
Labels: hacktoberfest-accepted, gssoc-ext, level1

#530 styling of icons
  auth.css
  auth.html
Labels: hacktoberfest-accepted, gssoc-ext, level1

#614 testimonials added
  index.html
  style.css
Labels: good first issue, hacktoberfest-accepted, gssoc-ext, level1

#753 fixed Header Bar Overlapping
  img/contact.css
  img/contact.html
  index.html
  style.css
Labels: hacktoberfest-accepted, gssoc-ext, level2

#762 Revert "fixed Header Bar Overlapping"
  img/contact.css
  img/contact.html
  index.html
  style.css
Labels: hacktoberfest-accepted

#873 Created Blog Page
  .github/workflows/autocomment-pr-merge.yml
  README.md
  blog.html
  index.html
Labels: hacktoberfest-accepted, gssoc-ext, level2

#1060 Fixed the Get in Touch with other buttons in homepage
  index.html
Labels: hacktoberfest-accepted, gssoc-ext, level1

#1081 cards redesigned
  book.html
  style.css
Labels: hacktoberfest-accepted, gssoc-ext, level1

#1085 Updated README.md added Video closes #1070
  README.md
  img/gssocextd1.jpg
  img/hacktoberfest1.png
Labels: documentation, hacktoberfest-accepted, gssoc-ext, level1

#1086 added the changes and checked for conflicts
  index.html
  style.css
Labels: hacktoberfest-accepted, gssoc-ext, level1

#1091 Disclaimer page created and linked in footer
  disclaimer.css
  disclaimer.html
  index.html
Labels: good first issue, hacktoberfest-accepted, gssoc-ext, level2
